# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'DatingApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DatingApp
  pod 'SwiftGen', '~> 6.5.1'
  pod 'Kingfisher'
  pod 'Localize-Swift'
  pod 'Alamofire'
  pod 'Toaster'
  pod 'IQKeyboardManagerSwift'
  pod 'ExytePopupView'

  target 'DatingAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DatingAppUITests' do
    # Pods for testing
  end

end
